from __future__ import annotations

from app.core.constants import ROLE_DISPLAY_NAMES, ROLE_HIERARCHY, RoleCode
from app.models.enums import PermissionCategory


BASE_MODULES = [
    "dashboard",
    "employees",
    "attendance",
    "leave",
    "payroll",
    "reports",
    "calendar",
    "notifications",
    "tracker",
    "settings",
]


def _permission(
    *,
    key: str,
    name: str,
    module: str,
    category: PermissionCategory,
    resource: str,
    action: str,
    description: str,
) -> dict[str, str]:
    return {
        "key": key,
        "name": name,
        "module": module,
        "category": category.value,
        "resource": resource,
        "action": action,
        "description": description,
    }


def build_permission_catalog() -> list[dict[str, str]]:
    permissions: list[dict[str, str]] = []

    for module in BASE_MODULES:
        title = module.replace("_", " ").title()
        permissions.extend(
            [
                _permission(
                    key=f"module.{module}.access",
                    name=f"{title} Module Access",
                    module=module,
                    category=PermissionCategory.MODULE,
                    resource=module,
                    action="access",
                    description=f"Allows access to the {title} module.",
                ),
                _permission(
                    key=f"menu.{module}.view",
                    name=f"{title} Menu Visibility",
                    module=module,
                    category=PermissionCategory.MENU,
                    resource=module,
                    action="view",
                    description=f"Shows the {title} item in navigation menus.",
                ),
                _permission(
                    key=f"page.{module}.view",
                    name=f"{title} Page Visibility",
                    module=module,
                    category=PermissionCategory.PAGE,
                    resource=module,
                    action="view",
                    description=f"Allows viewing the {title} pages.",
                ),
            ]
        )

    permissions.extend(
        [
            _permission(
                key="dashboard.view.personal",
                name="Personal Dashboard",
                module="dashboard",
                category=PermissionCategory.ACTION,
                resource="dashboard",
                action="view_personal",
                description="View personal employee dashboard widgets.",
            ),
            _permission(
                key="dashboard.view.team",
                name="Team Dashboard",
                module="dashboard",
                category=PermissionCategory.ACTION,
                resource="dashboard",
                action="view_team",
                description="View team-level dashboard widgets.",
            ),
            _permission(
                key="dashboard.view.hr",
                name="HR Dashboard",
                module="dashboard",
                category=PermissionCategory.ACTION,
                resource="dashboard",
                action="view_hr",
                description="View HR dashboard widgets and summaries.",
            ),
            _permission(
                key="dashboard.view.admin",
                name="Admin Dashboard",
                module="dashboard",
                category=PermissionCategory.ACTION,
                resource="dashboard",
                action="view_admin",
                description="View admin dashboard widgets and summaries.",
            ),
            _permission(
                key="dashboard.view.super_admin",
                name="Super Admin Dashboard",
                module="dashboard",
                category=PermissionCategory.ACTION,
                resource="dashboard",
                action="view_super_admin",
                description="View Super Admin dashboard widgets and system summaries.",
            ),
            _permission(
                key="employees.view",
                name="View Employees",
                module="employees",
                category=PermissionCategory.ACTION,
                resource="employee",
                action="view",
                description="View employee records.",
            ),
            _permission(
                key="employees.create",
                name="Create Employees",
                module="employees",
                category=PermissionCategory.ACTION,
                resource="employee",
                action="create",
                description="Create employee records.",
            ),
            _permission(
                key="employees.edit",
                name="Edit Employees",
                module="employees",
                category=PermissionCategory.ACTION,
                resource="employee",
                action="edit",
                description="Edit employee records.",
            ),
            _permission(
                key="employees.deactivate",
                name="Deactivate Employees",
                module="employees",
                category=PermissionCategory.ACTION,
                resource="employee",
                action="deactivate",
                description="Activate or deactivate employee records.",
            ),
            _permission(
                key="employees.assign_manager",
                name="Assign Reporting Manager",
                module="employees",
                category=PermissionCategory.ACTION,
                resource="employee",
                action="assign_manager",
                description="Assign or change reporting managers.",
            ),
            _permission(
                key="attendance.view.own",
                name="View Own Attendance",
                module="attendance",
                category=PermissionCategory.ACTION,
                resource="attendance",
                action="view_own",
                description="View own attendance records.",
            ),
            _permission(
                key="attendance.view.team",
                name="View Team Attendance",
                module="attendance",
                category=PermissionCategory.ACTION,
                resource="attendance",
                action="view_team",
                description="View team attendance records.",
            ),
            _permission(
                key="attendance.view.all",
                name="View All Attendance",
                module="attendance",
                category=PermissionCategory.ACTION,
                resource="attendance",
                action="view_all",
                description="View attendance records across the organization.",
            ),
            _permission(
                key="attendance.check_in",
                name="Attendance Check In",
                module="attendance",
                category=PermissionCategory.ACTION,
                resource="attendance",
                action="check_in",
                description="Perform attendance check-in.",
            ),
            _permission(
                key="attendance.check_out",
                name="Attendance Check Out",
                module="attendance",
                category=PermissionCategory.ACTION,
                resource="attendance",
                action="check_out",
                description="Perform attendance check-out.",
            ),
            _permission(
                key="attendance.correct",
                name="Attendance Corrections",
                module="attendance",
                category=PermissionCategory.CORRECTION,
                resource="attendance",
                action="correct",
                description="Correct attendance records and apply audit-logged adjustments.",
            ),
            _permission(
                key="attendance.rules.manage",
                name="Manage Attendance Rules",
                module="attendance",
                category=PermissionCategory.SETTING,
                resource="attendance_rule",
                action="manage",
                description="Manage late mark and half-day rule settings.",
            ),
            _permission(
                key="leave.apply",
                name="Apply Leave",
                module="leave",
                category=PermissionCategory.ACTION,
                resource="leave_request",
                action="apply",
                description="Apply for leave.",
            ),
            _permission(
                key="leave.view.own",
                name="View Own Leave",
                module="leave",
                category=PermissionCategory.ACTION,
                resource="leave_request",
                action="view_own",
                description="View own leave history.",
            ),
            _permission(
                key="leave.view.team",
                name="View Team Leave",
                module="leave",
                category=PermissionCategory.ACTION,
                resource="leave_request",
                action="view_team",
                description="View team leave requests.",
            ),
            _permission(
                key="leave.view.all",
                name="View All Leave",
                module="leave",
                category=PermissionCategory.ACTION,
                resource="leave_request",
                action="view_all",
                description="View leave requests across the organization.",
            ),
            _permission(
                key="leave.approve",
                name="Approve Leave",
                module="leave",
                category=PermissionCategory.APPROVAL,
                resource="leave_request",
                action="approve",
                description="Approve or reject leave requests.",
            ),
            _permission(
                key="leave.recommend",
                name="Recommend Leave",
                module="leave",
                category=PermissionCategory.APPROVAL,
                resource="leave_request",
                action="recommend",
                description="Recommend leave actions at team level.",
            ),
            _permission(
                key="payroll.view.own",
                name="View Own Payroll",
                module="payroll",
                category=PermissionCategory.ACTION,
                resource="payroll",
                action="view_own",
                description="View own payslips and payroll records.",
            ),
            _permission(
                key="payroll.view.all",
                name="View All Payroll",
                module="payroll",
                category=PermissionCategory.ACTION,
                resource="payroll",
                action="view_all",
                description="View payroll records across the organization.",
            ),
            _permission(
                key="payroll.manage",
                name="Manage Payroll",
                module="payroll",
                category=PermissionCategory.ACTION,
                resource="payroll",
                action="manage",
                description="Configure salary structures and run payroll.",
            ),
            _permission(
                key="payroll.download",
                name="Download Payslips",
                module="payroll",
                category=PermissionCategory.ACTION,
                resource="payslip",
                action="download",
                description="Download generated payslips.",
            ),
            _permission(
                key="reports.view",
                name="View Reports",
                module="reports",
                category=PermissionCategory.ACTION,
                resource="report",
                action="view",
                description="View reports and summaries.",
            ),
            _permission(
                key="reports.submit",
                name="Submit Reports",
                module="reports",
                category=PermissionCategory.ACTION,
                resource="report",
                action="submit",
                description="Submit employee reports for admin review.",
            ),
            _permission(
                key="reports.export.csv",
                name="Export CSV Reports",
                module="reports",
                category=PermissionCategory.EXPORT,
                resource="report",
                action="export_csv",
                description="Export report data as CSV.",
            ),
            _permission(
                key="notifications.view.own",
                name="View Notifications",
                module="notifications",
                category=PermissionCategory.ACTION,
                resource="notification",
                action="view_own",
                description="View personal notifications.",
            ),
            _permission(
                key="notifications.manage",
                name="Manage Notifications",
                module="notifications",
                category=PermissionCategory.ACTION,
                resource="notification",
                action="manage",
                description="Create and manage notifications.",
            ),
            _permission(
                key="tracker.monitor",
                name="Monitor Tracker",
                module="tracker",
                category=PermissionCategory.ACTION,
                resource="tracker",
                action="monitor",
                description="Monitor online employees, heartbeat state, and tracker activity.",
            ),
            _permission(
                key="tracker.view.device",
                name="View Tracker Devices",
                module="tracker",
                category=PermissionCategory.ACTION,
                resource="device",
                action="view",
                description="View registered tracker devices.",
            ),
            _permission(
                key="settings.roles.manage",
                name="Manage Roles",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="role",
                action="manage",
                description="Manage roles and hierarchy settings.",
            ),
            _permission(
                key="settings.permissions.manage",
                name="Manage Permissions",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="permission",
                action="manage",
                description="Manage role permissions and page visibility controls.",
            ),
            _permission(
                key="settings.app.manage",
                name="Manage App Settings",
                module="settings",
                category=PermissionCategory.SETTING,
                resource="app_setting",
                action="manage",
                description="Manage system-wide HRM rules and settings.",
            ),
            _permission(
                key="users.create",
                name="Create Users",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="user",
                action="create",
                description="Create new users.",
            ),
            _permission(
                key="users.edit",
                name="Edit Users",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="user",
                action="edit",
                description="Edit user profiles and credentials.",
            ),
            _permission(
                key="users.deactivate",
                name="Deactivate Users",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="user",
                action="deactivate",
                description="Deactivate or suspend users.",
            ),
            _permission(
                key="users.activate",
                name="Activate Users",
                module="settings",
                category=PermissionCategory.ACTION,
                resource="user",
                action="activate",
                description="Reactivate users.",
            ),
        ]
    )

    return permissions


PERMISSION_CATALOG = build_permission_catalog()
ALL_PERMISSION_KEYS = {item["key"] for item in PERMISSION_CATALOG}


DEFAULT_ROLE_PERMISSION_KEYS: dict[RoleCode, set[str]] = {
    RoleCode.SUPER_ADMIN: set(ALL_PERMISSION_KEYS),
    RoleCode.ADMIN: {
        "module.dashboard.access",
        "menu.dashboard.view",
        "page.dashboard.view",
        "dashboard.view.admin",
        "module.employees.access",
        "menu.employees.view",
        "page.employees.view",
        "employees.view",
        "employees.create",
        "employees.edit",
        "employees.assign_manager",
        "module.attendance.access",
        "menu.attendance.view",
        "page.attendance.view",
        "attendance.view.all",
        "attendance.check_in",
        "attendance.check_out",
        "attendance.correct",
        "module.leave.access",
        "menu.leave.view",
        "page.leave.view",
        "leave.apply",
        "leave.view.all",
        "leave.approve",
        "module.reports.access",
        "menu.reports.view",
        "page.reports.view",
        "reports.view",
        "reports.export.csv",
        "module.calendar.access",
        "menu.calendar.view",
        "page.calendar.view",
        "module.notifications.access",
        "menu.notifications.view",
        "page.notifications.view",
        "notifications.view.own",
        "notifications.manage",
        "module.tracker.access",
        "menu.tracker.view",
        "page.tracker.view",
        "tracker.monitor",
        "tracker.view.device",
    },
    RoleCode.HR: {
        "module.dashboard.access",
        "menu.dashboard.view",
        "page.dashboard.view",
        "dashboard.view.hr",
        "module.employees.access",
        "menu.employees.view",
        "page.employees.view",
        "employees.view",
        "employees.create",
        "employees.edit",
        "module.attendance.access",
        "menu.attendance.view",
        "page.attendance.view",
        "attendance.view.all",
        "attendance.check_in",
        "attendance.check_out",
        "attendance.correct",
        "module.leave.access",
        "menu.leave.view",
        "page.leave.view",
        "leave.apply",
        "leave.view.all",
        "leave.approve",
        "module.reports.access",
        "menu.reports.view",
        "page.reports.view",
        "reports.view",
        "reports.export.csv",
        "module.calendar.access",
        "menu.calendar.view",
        "page.calendar.view",
        "module.notifications.access",
        "menu.notifications.view",
        "page.notifications.view",
        "notifications.view.own",
        "module.tracker.access",
        "menu.tracker.view",
        "page.tracker.view",
        "tracker.monitor",
        "tracker.view.device",
    },
    RoleCode.TL: {
        "module.dashboard.access",
        "menu.dashboard.view",
        "page.dashboard.view",
        "dashboard.view.team",
        "module.attendance.access",
        "menu.attendance.view",
        "page.attendance.view",
        "attendance.view.team",
        "attendance.check_in",
        "attendance.check_out",
        "module.leave.access",
        "menu.leave.view",
        "page.leave.view",
        "leave.apply",
        "leave.view.own",
        "leave.view.team",
        "leave.recommend",
        "module.calendar.access",
        "menu.calendar.view",
        "page.calendar.view",
        "module.notifications.access",
        "menu.notifications.view",
        "page.notifications.view",
        "notifications.view.own",
        "module.tracker.access",
        "menu.tracker.view",
        "page.tracker.view",
        "tracker.monitor",
        "tracker.view.device",
    },
    RoleCode.EMPLOYEE: {
        "module.dashboard.access",
        "menu.dashboard.view",
        "page.dashboard.view",
        "dashboard.view.personal",
        "module.attendance.access",
        "menu.attendance.view",
        "page.attendance.view",
        "attendance.view.own",
        "attendance.check_in",
        "attendance.check_out",
        "module.leave.access",
        "menu.leave.view",
        "page.leave.view",
        "leave.apply",
        "leave.view.own",
        "module.reports.access",
        "menu.reports.view",
        "page.reports.view",
        "reports.submit",
        "module.payroll.access",
        "menu.payroll.view",
        "page.payroll.view",
        "payroll.view.own",
        "payroll.download",
        "module.calendar.access",
        "menu.calendar.view",
        "page.calendar.view",
        "module.notifications.access",
        "menu.notifications.view",
        "page.notifications.view",
        "notifications.view.own",
    },
}


def role_hierarchy_seed() -> list[dict[str, int | str]]:
    items: list[dict[str, int | str]] = []
    for index, code in enumerate(ROLE_HIERARCHY, start=1):
        items.append({"code": code.value, "name": ROLE_DISPLAY_NAMES[code], "hierarchy_rank": index})
    return items
